
interface ClassC
{
    attribute long v;
};

[Constructor()]
interface ClassB
{
    void Foo(long num);
};

[Constructor(),
 CppName=ClassBSub]
interface ClassBSubJS : ClassB
{
    void Bar(DOMString str);
};

[Constructor,
 Constructor(long x),
 Constructor(long x, ClassB y)]
interface ClassA
{
    static void StaticMethod();
    ClassB MakeAB();

    attribute long foo;
    readonly attribute long bar;

    static attribute long staticFoo;

    [Value] ClassC GetC();
    void SetC([Ref] ClassC v);
};

