[Constructor()]
interface ClassB
{
    void Foo(long num);
};

[Constructor,
 Constructor(long x),
 Constructor(long x, ClassB y)]
interface ClassA
{
    static void StaticMethod();
    ClassB MakeAB();
};

